### ISSUE TITLE
How to setup for an existing solution

### ISSUE THREAD

**Issue by exalted** [PrecisionWebTechnologies/DynamicMVC#1]
I already have an existing solution with two separate projects (one for the webapp and one for the model class library) and honestly can't get my head around how could I tie this whole thing together.

Ideally, what I would like to be able to have is an additional third project in my solution (let's call it `WebAppAdmin`), add a reference to the model class library (decorate my models with `DynamicEntityAttribute`) and... :boom: it just works!

Could you please shed some light here? Thanks.

**Comment by ChrisAdamPerry** [comment]
You are absolutely right that it should just poof and everything works.  This scenario is supported.  You do have to modify one line of code in the global file to let Dynamic MVC know you are using a different project for your business logic.  Unfortunately there is a bug in the latest release preventing this scenario from functioning properly.  I am looking into the issue.  I will have an ETA in about a week or so.  Sorry for the inconvenience.

**Comment by exalted** [comment]
Thanks. Looking forward to it. 🙏

## 

Ali

On Fri, Jun 17, 2016 at 5:51 AM +0200, "Chris Perry" notifications@github.com wrote:

You are absolutely right that it should just poof and everything works.  This scenario is supported.  You do have to modify one line of code in the global file to let Dynamic MVC know you are using a different project for your business logic.  Unfortunately there is a bug in the latest release preventing this scenario from functioning properly.  I am looking into the issue.  I will have an ETA in about a week or so.  Sorry for the inconvenience.

**Comment by exalted** [comment]
I am going to close this, but please feel free to re-open if interested.
