### ISSUE TITLE
InvalidOperationException following Tutorial #1 using included OrderEntryDemo solution

### ISSUE THREAD

**Issue by j5bart** [PrecisionWebTechnologies/DynamicMVC#2]
I have tried to follow the first tutorial (http://www.dynamicmvc.com/Tutorial/Details/1) regarding the creation of a Product dynamic entity and am getting an InvalidOperationException when I try to view the Dynamic > Product page.

Exception details as follows:

An exception of type 'System.InvalidOperationException' occurred in EntityFramework.dll but was not handled in user code

Additional information: The entity type Product is not part of the model for the current context.

Any suggestions? 

Unsure if related, but Package Manager did output the following whilst I got setup with EntityFramework. So looks like its using a slightly newer verion.

Successfully installed 'EntityFramework 6.1.3' to OrderEntryDemo
Removing package 'EntityFramework.6.1.1' from folder 'C:\temp\OrderEntryDemo\packages'
Removed package 'EntityFramework.6.1.1' from folder 'C:\temp\OrderEntryDemo\packages'

**Comment by ChrisAdamPerry** [comment]
Did you add this to your IdentityModel class:
`public DbSet<Product> Products { get;set;}`

Let me know if that resolves the issue.

**Comment by j5bart** [comment]
Thanks this does indeed resolve the issue. 

However, can I ask if there is a reason why this is not resolved dynamically?
There are methods available on the context that could try to get a set for a type without having to explicitly declare it. Example:
http://stackoverflow.com/questions/5308336/how-can-i-create-dbsett-dynamically-in-entity-framework

Thanks

**Comment by j5bart** [comment]
Sorry I hadn't appreciated its importance for EF Code First approach. Closing this issue - apologies for my ignorance.

**Comment by ChrisAdamPerry** [comment]
It is interesting because if you create an entity that is related to product, you don't need to add it.  Code first only needs the first one and the others will just work.
