### ISSUE TITLE
Dynamic Foriegn key cannot be found in entity Machine for property Mill

### ISSUE THREAD

**Issue by Fetto** [PrecisionWebTechnologies/DynamicMVC#3]
Hello!

Thank you for an interesting product!

This:
    public class Mill
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Machine> Machines { get; set; }
    }

```
[DynamicEntity]
public class Machine
{
    public int Id { get; set; }
    public Mill Mill { get; set; }
    public string Name { get; set; }
}
```

.....

```
        modelBuilder.Entity<Mill>()
            .Property(e => e.Name)
            .IsRequired();

        modelBuilder.Entity<Machine>()
            .HasRequired(e => e.Mill);
```

Gives this exception:
Dynamic Foriegn key cannot be found in entity Machine for property Mill

I'v tried several different names and a lot of fluent api, but can't get it to work.
Any idea?

Best regards,
Patrik

**Comment by ChrisAdamPerry** [comment]
Try MillId inside machine.

[DynamicEntity]
public class Machine
{
    public int Id { get; set; }
    public Mill Mill { get; set; }
    Public int MillId {get;set;}
    public string Name { get; set; }
}
