### ISSUE TITLE
Can't get HasTableAnnotation to work (fluent api)

### ISSUE THREAD

**Issue by Fetto** [PrecisionWebTechnologies/DynamicMVC#4]
For example: 

> modelBuilder.Entity<Property>().HasTableAnnotation("DynamicEntity", "ShowCreate = false");
> has no effect.

Best regards,
Patrik

**Comment by ChrisAdamPerry** [comment]
Model builder is specific to code first.  DynamicMVC is not connected to code first so tightly.  You must use attributes on your model classes for your changes to be picked up.  This also means that Dynamic MVC will work with any data access provider you prefer.
